In [1]:
import pandas as pd
import seaborn as sns

In [2]:
p_df=sns.load_dataset("penguins")

In [3]:
p_df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

### droping NAs and duplicates

In [10]:
p_df=p_df.dropna()

In [11]:
p_df=p_df.drop_duplicates()

### X-y split

In [12]:
X=p_df[["flipper_length_mm", "bill_depth_mm"]]
y=p_df[["body_mass_g"]]

### Train test split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

In [20]:
y_test

body_mass_g
30        3250.0
317       4875.0
79        4000.0
201       3675.0
63        4050.0
..           ...
247       5650.0
122       3450.0
146       4250.0
182       3200.0
96        3700.0

[84 rows x 1 columns]

### Model training

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lm=LinearRegression()
model=lm.fit(X_train,y_train)

In [24]:
model.coef_

array([[52.20343571, 13.10815533]])

In [25]:
model.intercept_

array([-6509.21617362])

### Predict mass of random penguin

In [27]:
random_penguin=X_test.sample()

In [29]:
model.predict(random_penguin)

array([[3914.26547837]])

### Create predictuons for test set

In [34]:
y_pred=model.predict(X_test)

In [35]:
y_pred=pd.DataFrame(y_pred)

In [39]:
y_test=y_test.reset_index(drop=True)

In [40]:
residuals_df=pd.concat([y_test, y_pred], axis=1)
residuals_df

body_mass_g            0
0        3250.0  3001.901576
1        4875.0  5271.325621
2        4000.0  3920.819556
3        3675.0  4053.835184
4        4050.0  3752.411909
..          ...          ...
79       5650.0  4911.144833
80       3450.0  2901.427151
81       4250.0  3653.248300
82       3200.0  3470.421682
83       3700.0  3653.248300

[84 rows x 2 columns]

In [44]:
residuals_df=residuals_df.rename(columns={"body_mass_g":"y_test", 0:"y_pred"})

In [45]:
residuals_df["residual"]=residuals_df["y_test"]-residuals_df["y_pred"]

In [46]:
residuals_df.head()

y_test       y_pred    residual
0  3250.0  3001.901576  248.098424
1  4875.0  5271.325621 -396.325621
2  4000.0  3920.819556   79.180444
3  3675.0  4053.835184 -378.835184
4  4050.0  3752.411909  297.588091

### Metrics calculating

In [47]:
mean_error=residuals_df["residual"].mean()

In [48]:
mean_error

0.4256712769183001

In [49]:
from sklearn.metrics import mean_squared_error as mse, mean_absolute_error as mae

In [50]:
mse(y_test, y_pred)

135012.91730727017

In [51]:
mae(y_test, y_pred)

295.239293718512

In [53]:
import numpy as np
np.sqrt(mse(y_test, y_pred))

367.44103922571054

In [54]:
y_pred.mean()

0    4184.990995
dtype: float64

In [57]:
np.sqrt(mse(y_test, y_pred))/y_test.mean()*100

body_mass_g    8.779079
dtype: float64

In [59]:
rmse=mse(y_test, y_pred, squared=False)

In [60]:
rmse

367.44103922571054